use udemy_delivery;
CREATE TABLE users(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(180) NOT NULL UNIQUE,
name VARCHAR(90) NOT NULL,
lastname VARCHAR (90) NOT NULL,
phone VARCHAR (90) NOT NULL UNIQUE,
image VARCHAR(255) NOT NULL,
password VARCHAR(90) NOT NULL,
create_at_ TIMESTAMP(0) NOT NULL,
update_at TIMESTAMP(0) NOT NULL

);